// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://novhbokmfkcoafdqghjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vdmhib2ttZmtjb2FmZHFnaGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDQzOTgsImV4cCI6MjA2ODQ4MDM5OH0.A8WxCQTpEG9lw2MKT9fbLwVLiN8GpAU4HpYH3Ms90vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});